### ISSUE TITLE
Do you encounter any running error when testing slowfast?

### ISSUE THREAD

**Issue by yangsusanyang** [luckcodingdog/slowfast_log#1]
Hi Luckcodingdog,

I saw you have tested slowfast algorithm successfully. I am trying to evaluate it as well. But when I test it on Linux machine with command line "python tools/run_net.py --cfg configs/AVA/c2/SLOWFAST_64x2_R101_50_50.yaml TEST.CHECKPOINT_FILE_PATH model/SLOWFAST_64x2_R101_50_50.pkl TRAIN.ENABLE False NUM_GPUS 1", it shows error message of "Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 147, in main
    test(cfg=cfg)
  File "/media/workspace_karl/slowfast/tools/test_net.py", line 138, in test
    convert_from_caffe2=cfg.TEST.CHECKPOINT_TYPE == "caffe2",
  File "/media/workspace_karl/slowfast/slowfast/utils/checkpoint.py", line 186, in load_checkpoint
    caffe2_checkpoint = pickle.load(f, encoding="latin1")
_pickle.UnpicklingError: unpickling stack underflow
"

I wonder if you make any changes of source codes or config file "configs/AVA/c2/SLOWFAST_64x2_R101_50_50.yaml" to make it run.

Many thanks for your kind reply!

**Comment by luckcodingdog** [comment]
Hi, you are welcome!
i just past the code :
  CHECKPOINT_TYPE: pytorch
at line of #62 of  configs/AVA/c2/SLOWFAST_64x2_R101_50_50.yaml.
It costs about 23G memory of GPU of titian rtx with just one clip.

**Comment by yangsusanyang** [comment]
Thank you very much for your reply!

Another error is encountered: "No such file or directory".

Did you ever modify "slowFast-master/slowfast/config/defaults.py"?

By debugging, I found the ANNOTATION_DIR is set to  "ANNOTATION_DIR: /mnt/vol/gfsai-flash3-east/ai-group/users/haoqifan/ava/frame_list/ " which is not match the path in my machine. It seems that ANNOTATION_DIR is assigned according to "slowFast-master/slowfast/config/defaults.py".

**Comment by luckcodingdog** [comment]
yes, i have modified AVA.FRAME_DIR/FRAME_LIST_DIR/ANNOTATION_DIR to my own path.
